# syntax=docker/dockerfile:1.5
FROM rust:1.74.0

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --release

ENTRYPOINT ["/app/target/release/tcp_echo_server"]