# syntax=docker/dockerfile:1.5
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN --mount=type=cache,mode=0755,target=/root/.cache/pip \
    pip install -U pip && \
    pip install -r requirements.txt


COPY app/ .

CMD ["uvicorn", "main:app" , "--host", "0.0.0.0", "--port", "80"]