FROM debian:12.4-slim
RUN mkdir -p /root/.cache
COPY rebuild-trigger .

RUN date
RUN --mount=type=cache,id=locked-cache,target=/root/.cache,sharing=locked \
  echo $(date):" locked2 Locked" && \ 
  echo $(date)": Hello from locked2" >> /root/.cache/locked.log && \
  sleep 10 && \
  echo "--- locked.log ---------" && \
  cat /root/.cache/locked.log && \
  echo "------------------------" && \
  echo $(date):" locked2 Unlocked" 

RUN date